//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO_AC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CALENDARIO_AC()
        {
            this.CALENDARIO_EX = new HashSet<CALENDARIO_EX>();
        }
    
        public short EJERCICIO { get; set; }
        public int PERIODO { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string TSOL_ID { get; set; }
        public System.DateTime PRE_FROMF { get; set; }
        public System.TimeSpan PRE_FROMH { get; set; }
        public System.DateTime PRE_TOF { get; set; }
        public System.TimeSpan PRE_TOH { get; set; }
        public System.DateTime CIE_FROMF { get; set; }
        public System.TimeSpan CIE_FROMH { get; set; }
        public System.DateTime CIE_TOF { get; set; }
        public System.TimeSpan CIE_TOH { get; set; }
        public string USUARIOC_ID { get; set; }
        public System.DateTime FECHAC { get; set; }
        public string USUARIOM_ID { get; set; }
        public Nullable<System.DateTime> FECHAM { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual PERIODO PERIODO1 { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        public virtual TSOL TSOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALENDARIO_EX> CALENDARIO_EX { get; set; }
    }
}
