//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO_EX
    {
        public short EJERCICIO { get; set; }
        public int PERIODO { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string TSOL_ID { get; set; }
        public string USUARIO_ID { get; set; }
        public System.DateTime EX_FROMF { get; set; }
        public System.TimeSpan EX_FROMH { get; set; }
        public System.DateTime EX_TOF { get; set; }
        public System.TimeSpan EX_TOH { get; set; }
        public string USUARIOC_ID { get; set; }
        public System.DateTime FEHAC { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CALENDARIO_AC CALENDARIO_AC { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
