//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARTA()
        {
            this.CARTAPs = new HashSet<CARTAP>();
        }
    
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public Nullable<System.DateTime> FECHAC { get; set; }
        public string USUARIO_ID { get; set; }
        public string TIPO { get; set; }
        public string COMPANY { get; set; }
        public Nullable<bool> COMPANYX { get; set; }
        public string TAXID { get; set; }
        public Nullable<bool> TAXIDX { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<bool> CONCEPTOX { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<bool> CLIENTEX { get; set; }
        public string PUESTO { get; set; }
        public Nullable<bool> PUESTOX { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<bool> DIRECCIONX { get; set; }
        public string FOLIO { get; set; }
        public Nullable<bool> FOLIOX { get; set; }
        public string LUGAR { get; set; }
        public Nullable<bool> LUGARX { get; set; }
        public string PAYER { get; set; }
        public Nullable<bool> PAYERX { get; set; }
        public string ESTIMADO { get; set; }
        public Nullable<bool> ESTIMADOX { get; set; }
        public string MECANICA { get; set; }
        public Nullable<bool> MECANICAX { get; set; }
        public string NOMBREE { get; set; }
        public Nullable<bool> NOMBREEX { get; set; }
        public string PUESTOE { get; set; }
        public Nullable<bool> PUESTOEX { get; set; }
        public string COMPANYC { get; set; }
        public Nullable<bool> COMPANYCX { get; set; }
        public string NOMBREC { get; set; }
        public Nullable<bool> NOMBRECX { get; set; }
        public string PUESTOC { get; set; }
        public Nullable<bool> PUESTOCX { get; set; }
        public string COMPANYCC { get; set; }
        public Nullable<bool> COMPANYCCX { get; set; }
        public string LEGAL { get; set; }
        public Nullable<bool> LEGALX { get; set; }
        public string MAIL { get; set; }
        public Nullable<bool> MAILX { get; set; }
        public string LUGARFECH { get; set; }
        public Nullable<bool> LUGARFECHX { get; set; }
        public string MONTO { get; set; }
        public string MONEDA { get; set; }
        public string PAYERNOM { get; set; }
        public Nullable<bool> PAYERNOMX { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<bool> COMENTARIOX { get; set; }
        public string COMPROMISOK { get; set; }
        public Nullable<bool> COMPROMISOKX { get; set; }
        public string COMPROMISOC { get; set; }
        public Nullable<bool> COMPROMISOCX { get; set; }
        public Nullable<bool> SECOND_TABX { get; set; }
        public Nullable<bool> COSTO_UNX { get; set; }
        public Nullable<bool> APOYOX { get; set; }
        public Nullable<bool> APOYOPX { get; set; }
        public Nullable<bool> COSTOAPX { get; set; }
        public Nullable<bool> PRECIOX { get; set; }
        public Nullable<bool> APOYO_ESTX { get; set; }
        public Nullable<bool> APOYO_REAX { get; set; }
        public Nullable<bool> VOLUMEN_ESTX { get; set; }
        public Nullable<bool> VOLUMEN_REAX { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAP> CARTAPs { get; set; }
    }
}
