//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFDIST_CAT
    {
        public string SOCIEDAD_ID { get; set; }
        public string CAMPO { get; set; }
        public Nullable<bool> PORC_AD { get; set; }
        public Nullable<int> PERIODOS { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual CAMPOZKE24 CAMPOZKE24 { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
    }
}
