//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFDIST_CAT
    {
        public string SOCIEDAD_ID { get; set; }
        public string CAMPO { get; set; }
        public Nullable<bool> PORC_AD { get; set; }
        public Nullable<int> PERIODOS { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual CAMPOZKE24 CAMPOZKE24 { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
    }
}
