//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONPOSAPP
    {
        public decimal CONSECUTIVO { get; set; }
        public int POSICION { get; set; }
        public Nullable<int> RELACION { get; set; }
        public string KEY { get; set; }
        public string BUS_AREA { get; set; }
        public string POSTING_KEY { get; set; }
        public Nullable<bool> NUM_PROV { get; set; }
        public Nullable<bool> NUM_CTE { get; set; }
        public Nullable<bool> CTA_MAYOR { get; set; }
        public Nullable<bool> CTA_MAYOR_FV { get; set; }
        public Nullable<bool> CECO { get; set; }
        public string TEXTO { get; set; }
        public Nullable<bool> SALES_ORG { get; set; }
        public Nullable<bool> CAN_DIST { get; set; }
        public Nullable<bool> DIVISION { get; set; }
        public Nullable<bool> SALES_OFF { get; set; }
        public Nullable<bool> SALES_GRP { get; set; }
        public Nullable<bool> PRICE_GRP { get; set; }
        public Nullable<bool> CORP_CAT { get; set; }
        public Nullable<bool> CORP_BRAND { get; set; }
        public Nullable<bool> INV_REF { get; set; }
        public Nullable<bool> PAYM_TERM { get; set; }
        public Nullable<bool> JURIS_CODE { get; set; }
        public Nullable<bool> SALES_DIST { get; set; }
        public Nullable<bool> PRODUCT { get; set; }
        public string TAX_CODE { get; set; }
        public Nullable<bool> PLANT { get; set; }
        public string REF_KEY1 { get; set; }
        public string REF_KEY3 { get; set; }
        public Nullable<bool> ASSIGNACION { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string BASE_UNIT { get; set; }
        public string MATERIALGP { get; set; }
        public string TAXCODEGP { get; set; }
        public string ASIGNACIONTXT { get; set; }
    }
}
