//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONPOSAPH
    {
        public decimal CONSECUTIVO { get; set; }
        public string TIPO_SOL { get; set; }
        public string TIPO_DOC { get; set; }
        public string SOCIEDAD { get; set; }
        public string FECHA_CONTAB { get; set; }
        public string FECHA_DOCU { get; set; }
        public string MONEDA { get; set; }
        public string HEADER_TEXT { get; set; }
        public Nullable<System.DateTime> FECHA_INIVIG { get; set; }
        public Nullable<System.DateTime> FECHA_FINVIG { get; set; }
        public string REFERENCIA { get; set; }
        public string PAIS { get; set; }
        public string NOTA { get; set; }
        public string CORRESPONDENCIA { get; set; }
        public Nullable<bool> CALC_TAXT { get; set; }
        public Nullable<int> RELACION { get; set; }
        public string RETENCION { get; set; }
        public string DESCRI_CONFIG { get; set; }
    
        public virtual SOCIEDAD SOCIEDAD1 { get; set; }
    }
}
