//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTOC
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string KUNNR { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<bool> DEFECTO { get; set; }
        public Nullable<bool> CARTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
