//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTOC
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string KUNNR { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<bool> DEFECTO { get; set; }
        public Nullable<bool> CARTA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
