//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREADOR2
    {
        public string ID { get; set; }
        public int PUESTOC_ID { get; set; }
        public int POS { get; set; }
        public long AGROUP_ID { get; set; }
        public bool ACTIVO { get; set; }
        public string BUKRS { get; set; }
        public string LAND { get; set; }
    }
}
