//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_AGENTEP
    {
        public string SOCIEDAD_ID { get; set; }
        public int PUESTOC_ID { get; set; }
        public int VERSION { get; set; }
        public long AGROUP_ID { get; set; }
        public int POS { get; set; }
        public Nullable<int> PUESTOA_ID { get; set; }
        public string USUARIOA_ID { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<bool> PRESUPUESTO { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual DET_AGENTEH DET_AGENTEH { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
