//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_APROBH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DET_APROBH()
        {
            this.DET_APROBP = new HashSet<DET_APROBP>();
        }
    
        public string SOCIEDAD_ID { get; set; }
        public int PUESTOC_ID { get; set; }
        public int VERSION { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual PUESTO PUESTO { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DET_APROBP> DET_APROBP { get; set; }
    }
}
