//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOAYUDA
    {
        public string ID_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public int ID_CLASIFICACION { get; set; }
        public bool ACTIVO { get; set; }
        public string RUTA_DOCUMENTO { get; set; }
    
        public virtual DOCTOCLASIF DOCTOCLASIF { get; set; }
    }
}
