//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOAYUDA
    {
        public string ID_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public int ID_CLASIFICACION { get; set; }
        public bool ACTIVO { get; set; }
        public string RUTA_DOCUMENTO { get; set; }
    
        public virtual DOCTOCLASIF DOCTOCLASIF { get; set; }
    }
}
