//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTORAN
    {
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public int LIN { get; set; }
        public Nullable<decimal> OBJETIVOI { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
    
        public virtual DOCUMENTOREC DOCUMENTOREC { get; set; }
    }
}
