//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOL
    {
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public Nullable<System.DateTime> FECHAF { get; set; }
        public Nullable<decimal> MONTO_VENTA { get; set; }
        public Nullable<bool> ESTATUS { get; set; }
        public Nullable<decimal> BACKORDER { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
