//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOT
    {
        public decimal NUM_DOC { get; set; }
        public int TSFORM_ID { get; set; }
        public Nullable<bool> CHECKS { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual TS_CAMPO TS_CAMPO { get; set; }
    }
}
