//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOM
    {
        public decimal NUM_DOC { get; set; }
        public decimal POS_ID { get; set; }
        public int POS { get; set; }
        public string MATNR { get; set; }
        public Nullable<decimal> PORC_APOYO { get; set; }
        public Nullable<decimal> APOYO_EST { get; set; }
        public Nullable<decimal> APOYO_REAL { get; set; }
        public Nullable<System.DateTime> VIGENCIA_DE { get; set; }
        public Nullable<System.DateTime> VIGENCIA_A { get; set; }
        public Nullable<decimal> VALORH { get; set; }
    
        public virtual DOCUMENTOP DOCUMENTOP { get; set; }
    }
}
