//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTORAN
    {
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public int LIN { get; set; }
        public Nullable<decimal> OBJETIVOI { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
    
        public virtual DOCUMENTOREC DOCUMENTOREC { get; set; }
    }
}
