//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASCONF
    {
        public string SOCIEDAD_ID { get; set; }
        public string PAIS_ID { get; set; }
        public string TSOL { get; set; }
        public bool FACTURA { get; set; }
        public bool FECHA { get; set; }
        public bool PROVEEDOR { get; set; }
        public bool CONTROL { get; set; }
        public bool AUTORIZACION { get; set; }
        public bool VENCIMIENTO { get; set; }
        public bool FACTURAK { get; set; }
        public bool EJERCICIOK { get; set; }
        public bool BILL_DOC { get; set; }
        public bool BELNR { get; set; }
        public bool IMPORTE_FAC { get; set; }
        public bool PAYER { get; set; }
        public bool DESCRIPCION { get; set; }
        public bool SOCIEDAD { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual SOCIEDAD SOCIEDAD1 { get; set; }
    }
}
