//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJNEGO
    {
        public decimal NUM_DOC { get; set; }
        public int POS { get; set; }
        public string KUNNR { get; set; }
        public Nullable<System.DateTime> FECHAC { get; set; }
        public Nullable<System.DateTime> FECHAM { get; set; }
        public string COMENTARIO { get; set; }
    }
}
