//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAYOUT_CARGA
    {
        public int ID { get; set; }
        public string LAND { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string RUTA { get; set; }
        public System.DateTime FECHAC { get; set; }
        public string TIPO { get; set; }
    
        public virtual PAI PAI { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
    }
}
