//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALVKE
    {
        public string MATERIAL_ID { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
