//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE
    {
        public int ID_MENSAJE { get; set; }
        public string SPRAS { get; set; }
        public int PAGINA_ID { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
