//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE
    {
        public int ID_MENSAJE { get; set; }
        public string SPRAS { get; set; }
        public int PAGINA_ID { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
