//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEGOCIACION
    {
        public long ID { get; set; }
        public System.DateTime FECHAI { get; set; }
        public System.DateTime FECHAF { get; set; }
        public System.DateTime FECHAN { get; set; }
        public bool ACTIVO { get; set; }
    }
}
