//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEGOCIACION2
    {
        public int ID { get; set; }
        public string TITULO { get; set; }
        public System.DateTime FINICIO { get; set; }
        public string FRECUENCIA { get; set; }
        public int FRECUENCIA_N { get; set; }
        public string DIA_SEMANA { get; set; }
        public Nullable<int> DIA_MES { get; set; }
        public Nullable<int> ORDINAL_MES { get; set; }
        public string ORDINAL_DSEMANA { get; set; }
    }
}
