//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGINAV
    {
        public string ID { get; set; }
        public int PAGINA_ID { get; set; }
        public string PAGINA_URL { get; set; }
        public string TXT50 { get; set; }
        public int CARPETA_ID { get; set; }
        public string CARPETA_URL { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> PERMISO { get; set; }
        public string SPRAS_ID { get; set; }
        public string USUARIO_SPRAS { get; set; }
        public Nullable<int> Mantenimiento { get; set; }
        public string ManttoText { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string GrupoText { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
