//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIODO445
    {
        public int EJERCICIO { get; set; }
        public int MES_NATURAL { get; set; }
        public int DIA_NATURAL { get; set; }
        public int PERIODO { get; set; }
        public bool ACTIVO { get; set; }
        public int SUMA { get; set; }
    }
}
