//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTOP
    {
        public int ID { get; set; }
        public string ANIO { get; set; }
        public int POS { get; set; }
        public string MES { get; set; }
        public string VERSION { get; set; }
        public string PAIS { get; set; }
        public string REGION { get; set; }
        public string MONEDA { get; set; }
        public string MATERIAL { get; set; }
        public string BANNER { get; set; }
        public Nullable<double> ADVER { get; set; }
        public Nullable<double> CONPR { get; set; }
        public Nullable<double> CSHDC { get; set; }
        public Nullable<double> DIRLB { get; set; }
        public Nullable<double> DSTRB { get; set; }
        public Nullable<double> FREEG { get; set; }
        public Nullable<double> GRSLS { get; set; }
        public Nullable<double> NETLB { get; set; }
        public Nullable<double> OVHDF { get; set; }
        public Nullable<double> OVHDV { get; set; }
        public Nullable<double> PKGMT { get; set; }
        public Nullable<double> PMVAR { get; set; }
        public Nullable<double> POP { get; set; }
        public Nullable<double> PURCH { get; set; }
        public Nullable<double> RAWMT { get; set; }
        public Nullable<double> RECUN { get; set; }
        public Nullable<double> RSRDV { get; set; }
        public Nullable<double> TOTCS { get; set; }
        public Nullable<double> VVX17 { get; set; }
        public Nullable<double> OTHTA { get; set; }
        public Nullable<double> CORPM { get; set; }
        public Nullable<double> SPA { get; set; }
    
        public virtual PRESUPUESTOH PRESUPUESTOH { get; set; }
    }
}
