//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CAMPO
    {
        public string TAB_ID { get; set; }
        public string CAMPO_ID { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual TAB TAB { get; set; }
    }
}
