//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CAMPO
    {
        public string TAB_ID { get; set; }
        public string CAMPO_ID { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual TAB TAB { get; set; }
    }
}
