//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAX_LAND
    {
        public string SOCIEDAD_ID { get; set; }
        public string PAIS_ID { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual PAI PAI { get; set; }
    }
}
