//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXEOH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAXEOH()
        {
            this.TAXEOPs = new HashSet<TAXEOP>();
        }
    
        public string SOCIEDAD_ID { get; set; }
        public string PAIS_ID { get; set; }
        public string VKORG { get; set; }
        public string VTWEG { get; set; }
        public string SPART { get; set; }
        public string KUNNR { get; set; }
        public int CONCEPTO_ID { get; set; }
        public Nullable<int> TNOTA_ID { get; set; }
        public Nullable<System.DateTime> FECHAC { get; set; }
        public string USUARIOC_ID { get; set; }
        public Nullable<System.DateTime> FECHAM { get; set; }
        public string USUARIOM_ID { get; set; }
        public string IMPUESTO_ID { get; set; }
        public Nullable<decimal> PORC { get; set; }
        public string PAY_T { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual IMPUESTO IMPUESTO { get; set; }
        public virtual PAI PAI { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        public virtual TX_CONCEPTO TX_CONCEPTO { get; set; }
        public virtual TX_TNOTA TX_TNOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAXEOP> TAXEOPs { get; set; }
    }
}
