//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_FORM
    {
        public int ID { get; set; }
        public string BUKRS_ID { get; set; }
        public string LAND_ID { get; set; }
        public int POS { get; set; }
        public string CAMPO { get; set; }
    
        public virtual PAI PAI { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        public virtual TS_CAMPO TS_CAMPO { get; set; }
    }
}
