//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_FORM
    {
        public int ID { get; set; }
        public string BUKRS_ID { get; set; }
        public string LAND_ID { get; set; }
        public int POS { get; set; }
        public string CAMPO { get; set; }
    
        public virtual PAI PAI { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        public virtual TS_CAMPO TS_CAMPO { get; set; }
    }
}
