//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOL_GROUP
    {
        public string ID { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_PADRE { get; set; }
        public string TIPO_PADRE { get; set; }
    }
}
