//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSOL()
        {
            this.CALENDARIO_AC = new HashSet<CALENDARIO_AC>();
            this.CONSOPORTEs = new HashSet<CONSOPORTE>();
            this.DOCUMENTOes = new HashSet<DOCUMENTO>();
            this.TSOL1 = new HashSet<TSOL>();
            this.TSOLTs = new HashSet<TSOLT>();
        }
    
        public string ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string TSOLR { get; set; }
        public string RANGO_ID { get; set; }
        public string ESTATUS { get; set; }
        public bool FACTURA { get; set; }
        public bool PADRE { get; set; }
        public bool ADICIONA { get; set; }
        public string TSOLM { get; set; }
        public string TSOLC { get; set; }
        public string TRECU { get; set; }
        public bool NEGO { get; set; }
        public bool CARTA { get; set; }
        public bool REVERSO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALENDARIO_AC> CALENDARIO_AC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSOPORTE> CONSOPORTEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
        public virtual RANGO RANGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSOL> TSOL1 { get; set; }
        public virtual TSOL TSOL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSOLT> TSOLTs { get; set; }
    }
}
