//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSOL_GROUP
    {
        public string ID { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_PADRE { get; set; }
        public string TIPO_PADRE { get; set; }
    }
}
