//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMEDIDAT
    {
        public string SPRAS_ID { get; set; }
        public string MSEHI { get; set; }
        public string MSEH3 { get; set; }
        public string MSEH6 { get; set; }
        public string MSEHT { get; set; }
        public string MSEHL { get; set; }
    
        public virtual SPRA SPRA { get; set; }
        public virtual UMEDIDA UMEDIDA { get; set; }
    }
}
