//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOLOG
    {
        public string USUARIO_ID { get; set; }
        public Nullable<int> POS { get; set; }
        public string SESION { get; set; }
        public string NAVEGADOR { get; set; }
        public string UBICACION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<bool> LOGIN { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
