//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNINGP
    {
        public string TAB_ID { get; set; }
        public string ID { get; set; }
        public string DESCR { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string TSOL_ID { get; set; }
        public string TIPO { get; set; }
        public string CAMPOVAL_ID { get; set; }
        public Nullable<int> PAGINA_ID { get; set; }
        public string CAMPO_ID { get; set; }
        public string ACCION { get; set; }
    
        public virtual TAB TAB { get; set; }
    }
}
