//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNING_COND
    {
        public string TAB_ID { get; set; }
        public string WARNING_ID { get; set; }
        public int POS { get; set; }
        public string ANDOR { get; set; }
        public Nullable<int> CONDICION_ID { get; set; }
        public string VALOR_COMP { get; set; }
        public string ORAND { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual CONDICION CONDICION { get; set; }
    }
}
