//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAT001.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNINGP
    {
        public string TAB_ID { get; set; }
        public string ID { get; set; }
        public string DESCR { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string TSOL_ID { get; set; }
        public string TIPO { get; set; }
        public string CAMPOVAL_ID { get; set; }
        public Nullable<int> PAGINA_ID { get; set; }
        public string CAMPO_ID { get; set; }
        public string ACCION { get; set; }
    
        public virtual TAB TAB { get; set; }
    }
}
